//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klazor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pinhua2.BlazorApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Must be between 1 and 12 的本地化字符串。
        /// </summary>
        internal static string Between_1_and_12 {
            get {
                return ResourceManager.GetString("Between 1 and 12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must be \&quot;auto\&quot; or between 1 and 12 的本地化字符串。
        /// </summary>
        internal static string Between_1_and_12_Auto {
            get {
                return ResourceManager.GetString("Between 1 and 12 Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must be \&quot;last\&quot;, \&quot;first\&quot;, or between 1 and 12 的本地化字符串。
        /// </summary>
        internal static string Between_1_and_12_Last_First {
            get {
                return ResourceManager.GetString("Between 1 and 12 Last First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cannot be empty 的本地化字符串。
        /// </summary>
        internal static string cannot_be_empty {
            get {
                return ResourceManager.GetString("cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not parse input. Invalid Guid format. 的本地化字符串。
        /// </summary>
        internal static string Could_not_parse_input__Invalid_Guid_format {
            get {
                return ResourceManager.GetString("Could not parse input. Invalid Guid format", resourceCulture);
            }
        }
    }
}
