// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pinhua2.Data;

namespace Pinhua2.Data.Migrations
{
    [DbContext(typeof(Pinhua2Context))]
    [Migration("20190518133424_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pinhua2.Data.Models.sysAutoCode", b =>
                {
                    b.Property<int>("AutoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AllowBatch");

                    b.Property<int?>("AllowMore");

                    b.Property<string>("AutoCodeName");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<string>("DateType");

                    b.Property<int?>("IsActive");

                    b.Property<string>("Memo");

                    b.Property<string>("Prefix");

                    b.Property<int?>("ReuseType");

                    b.Property<int?>("RunBeforeSave");

                    b.Property<int?>("SeedLength");

                    b.Property<int?>("SeedStart");

                    b.Property<int?>("SysVar");

                    b.HasKey("AutoCodeId");

                    b.ToTable("sysAutoCode");

                    b.HasData(
                        new
                        {
                            AutoCodeId = 100,
                            AutoCodeName = "订单号",
                            CreateUser = 2,
                            DateType = "yyMM",
                            IsActive = 1,
                            RunBeforeSave = 1,
                            SeedLength = 4,
                            SeedStart = 1
                        },
                        new
                        {
                            AutoCodeId = 101,
                            AutoCodeName = "子单号",
                            CreateUser = 2,
                            DateType = "yy",
                            IsActive = 1,
                            RunBeforeSave = 1,
                            SeedLength = 6,
                            SeedStart = 1
                        },
                        new
                        {
                            AutoCodeId = 200,
                            AutoCodeName = "商品号",
                            CreateUser = 2,
                            IsActive = 1,
                            Prefix = "10",
                            RunBeforeSave = 1,
                            SeedLength = 8,
                            SeedStart = 1
                        },
                        new
                        {
                            AutoCodeId = 300,
                            AutoCodeName = "往来号",
                            CreateUser = 2,
                            DateType = "yy",
                            IsActive = 1,
                            RunBeforeSave = 1,
                            SeedLength = 4,
                            SeedStart = 1
                        },
                        new
                        {
                            AutoCodeId = 400,
                            AutoCodeName = "档案号",
                            CreateUser = 2,
                            DateType = "yy",
                            IsActive = 1,
                            RunBeforeSave = 1,
                            SeedLength = 4,
                            SeedStart = 1
                        });
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sysAutoCodeRegister", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AutoCodeId");

                    b.Property<int?>("CurrentSeed");

                    b.Property<string>("PrimaryPart");

                    b.HasKey("Idx");

                    b.ToTable("sysAutoCodeRegister");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sysIO", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("仓");

                    b.Property<string>("保修类型");

                    b.Property<string>("制单");

                    b.Property<string>("单号");

                    b.Property<string>("备注");

                    b.Property<string>("往来");

                    b.Property<string>("往来号");

                    b.Property<DateTime?>("日期");

                    b.Property<string>("物流单号");

                    b.Property<string>("类型");

                    b.Property<string>("订单号");

                    b.Property<decimal?>("退单")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("RecordId");

                    b.ToTable("sysIO");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sysIO_D", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<string>("仓");

                    b.Property<decimal?>("单价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("单位");

                    b.Property<decimal?>("发")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("品号");

                    b.Property<string>("品名");

                    b.Property<string>("品牌");

                    b.Property<string>("备注");

                    b.Property<string>("子单号");

                    b.Property<decimal?>("已完数")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("库位");

                    b.Property<string>("库存");

                    b.Property<string>("批次");

                    b.Property<decimal?>("收")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("日期");

                    b.Property<string>("日期唛");

                    b.Property<string>("条码");

                    b.Property<string>("版本号");

                    b.Property<decimal?>("税率")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("行号");

                    b.Property<string>("规格");

                    b.Property<decimal?>("计划数")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("订单号");

                    b.Property<decimal?>("质保")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("金额")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Idx");

                    b.ToTable("sysIO_D");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys付款条件表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.HasKey("RecordId");

                    b.ToTable("sys付款条件表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys员工表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<DateTime?>("入职日期");

                    b.Property<DateTime?>("合同到期日期");

                    b.Property<DateTime?>("合同签订日期");

                    b.Property<string>("地址");

                    b.Property<decimal?>("基本工资")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("姓名");

                    b.Property<string>("婚姻");

                    b.Property<string>("学历");

                    b.Property<string>("宅电");

                    b.Property<string>("属性");

                    b.Property<string>("工号");

                    b.Property<string>("性别");

                    b.Property<string>("手机");

                    b.Property<string>("是否签合同");

                    b.Property<string>("是否购社保");

                    b.Property<string>("状态");

                    b.Property<DateTime?>("生日");

                    b.Property<string>("电话");

                    b.Property<DateTime?>("社保开始日期");

                    b.Property<DateTime?>("社保退交日期");

                    b.Property<DateTime?>("离职日期");

                    b.Property<string>("紧急联系人");

                    b.Property<string>("紧急联系人关系");

                    b.Property<string>("紧急联系人地址");

                    b.Property<string>("紧急联系方式");

                    b.Property<string>("职位");

                    b.Property<string>("身份证号");

                    b.Property<string>("部门");

                    b.HasKey("RecordId");

                    b.ToTable("sys员工表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys商品表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("上级品号");

                    b.Property<string>("上级品名");

                    b.Property<string>("供应商");

                    b.Property<string>("供应商号");

                    b.Property<string>("分类1");

                    b.Property<string>("分类2");

                    b.Property<string>("别名");

                    b.Property<string>("单位");

                    b.Property<decimal?>("单重")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("反面颜色");

                    b.Property<string>("品号");

                    b.Property<string>("品名");

                    b.Property<string>("品牌");

                    b.Property<string>("商品信息");

                    b.Property<string>("图片");

                    b.Property<int?>("图片I");

                    b.Property<DateTime?>("填报时间");

                    b.Property<string>("备注");

                    b.Property<string>("复制");

                    b.Property<string>("大类");

                    b.Property<decimal?>("安全库存")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("客户");

                    b.Property<string>("客户号");

                    b.Property<string>("客户料号");

                    b.Property<string>("库位");

                    b.Property<string>("拼音码");

                    b.Property<decimal?>("指定销售价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("换算单位");

                    b.Property<decimal?>("换算系数")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("是否共用");

                    b.Property<string>("是否卷筒");

                    b.Property<string>("是否存储");

                    b.Property<string>("是否新旧");

                    b.Property<string>("是否采购");

                    b.Property<string>("是否销售");

                    b.Property<decimal?>("最新采购价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("材质");

                    b.Property<string>("条码");

                    b.Property<string>("档案号");

                    b.Property<string>("正面颜色");

                    b.Property<string>("版本号");

                    b.Property<string>("状态");

                    b.Property<string>("色号");

                    b.Property<string>("表面处理");

                    b.Property<string>("规格");

                    b.Property<string>("计算公式");

                    b.Property<decimal?>("质保")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("配比值")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("采购价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("采购周期")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("链接");

                    b.Property<decimal?>("销售价")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("RecordId");

                    b.ToTable("sys商品表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys地址表", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<string>("地址");

                    b.Property<string>("往来号");

                    b.Property<string>("电话");

                    b.Property<string>("联系人");

                    b.HasKey("Idx");

                    b.ToTable("sys往来表_地址");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys字典表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("创建人");

                    b.Property<DateTime?>("创建日");

                    b.Property<string>("字典名");

                    b.Property<string>("组");

                    b.HasKey("RecordId");

                    b.ToTable("sys字典表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys字典表_D", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("RN")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<string>("代码");

                    b.Property<string>("名称");

                    b.Property<string>("字典名");

                    b.Property<string>("描述");

                    b.Property<string>("组");

                    b.HasKey("Idx");

                    b.ToTable("sys字典表_D");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys工序表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.HasKey("RecordId");

                    b.ToTable("sys工序表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys开票表", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<string>("发票抬头");

                    b.Property<string>("往来号");

                    b.Property<string>("税号");

                    b.Property<string>("账号");

                    b.HasKey("Idx");

                    b.ToTable("sys往来表_开票");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys往来表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<string>("Qq");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("付款方式");

                    b.Property<string>("传真");

                    b.Property<decimal?>("信用额")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("全称");

                    b.Property<string>("公司电话");

                    b.Property<string>("地址");

                    b.Property<string>("币种");

                    b.Property<string>("开户行");

                    b.Property<string>("往来号");

                    b.Property<string>("状态");

                    b.Property<DateTime?>("登记日期");

                    b.Property<string>("登记部门");

                    b.Property<string>("税收组");

                    b.Property<string>("简称");

                    b.Property<string>("类型");

                    b.Property<string>("组织代码");

                    b.Property<string>("联系人");

                    b.Property<string>("联系电话");

                    b.Property<string>("负责人");

                    b.Property<string>("账号");

                    b.HasKey("RecordId");

                    b.ToTable("sys往来表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys报价表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("业务类型");

                    b.Property<DateTime?>("交期");

                    b.Property<string>("仓");

                    b.Property<string>("制单");

                    b.Property<string>("单号");

                    b.Property<string>("备注");

                    b.Property<string>("往来");

                    b.Property<string>("往来单号");

                    b.Property<string>("往来号");

                    b.Property<DateTime?>("日期");

                    b.Property<string>("需求单");

                    b.HasKey("RecordId");

                    b.ToTable("sys报价表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys报价表_D", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<decimal?>("上次价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("上次日期");

                    b.Property<decimal?>("单价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("单位");

                    b.Property<string>("品号");

                    b.Property<string>("品名");

                    b.Property<string>("品牌");

                    b.Property<string>("备注");

                    b.Property<string>("子单号");

                    b.Property<decimal?>("库存")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("数量")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("状态");

                    b.Property<decimal?>("税率")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("行号");

                    b.Property<string>("规格");

                    b.Property<decimal?>("金额")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Idx");

                    b.ToTable("sys报价表_D");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys收付表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<decimal?>("付")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("分配")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("制单");

                    b.Property<string>("单号");

                    b.Property<string>("发票号");

                    b.Property<string>("备注");

                    b.Property<string>("往来");

                    b.Property<string>("往来号");

                    b.Property<decimal?>("收")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("日期");

                    b.Property<string>("类型");

                    b.HasKey("RecordId");

                    b.ToTable("sys收付表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys收付表_D", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<string>("单位");

                    b.Property<decimal?>("可收付款额")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("备注");

                    b.Property<string>("子单号");

                    b.Property<decimal?>("已收付款数")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("已收付款额")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("待收付款额")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("描述");

                    b.Property<decimal?>("收发数")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("收发额")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("数量")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("本次付数")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("本次付额")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("本次收数")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("本次收额")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("金额")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Idx");

                    b.ToTable("sys收付表_D");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys班组表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.HasKey("RecordId");

                    b.ToTable("sys班组表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys联系人表", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Qq");

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<string>("传真");

                    b.Property<string>("备注");

                    b.Property<string>("往来号");

                    b.Property<string>("手机");

                    b.Property<string>("电话");

                    b.Property<string>("职位");

                    b.Property<string>("联系人");

                    b.Property<string>("部门");

                    b.HasKey("Idx");

                    b.ToTable("sys往来表_联系人");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys订单表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("业务类型");

                    b.Property<DateTime?>("交期");

                    b.Property<string>("仓");

                    b.Property<string>("制单");

                    b.Property<string>("单号");

                    b.Property<string>("备注");

                    b.Property<decimal?>("应付")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("应收")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("往来");

                    b.Property<string>("往来单号");

                    b.Property<string>("往来号");

                    b.Property<string>("报价单");

                    b.Property<DateTime?>("日期");

                    b.HasKey("RecordId");

                    b.ToTable("sys订单表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys订单表_D", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<decimal?>("单价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("单位");

                    b.Property<string>("品号");

                    b.Property<string>("品名");

                    b.Property<string>("品牌");

                    b.Property<string>("备注");

                    b.Property<string>("子单号");

                    b.Property<decimal?>("库存")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("数量")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("新价日期");

                    b.Property<decimal?>("最新价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("状态");

                    b.Property<decimal?>("税率")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("行号");

                    b.Property<string>("规格");

                    b.Property<string>("质保");

                    b.Property<decimal?>("金额")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Idx");

                    b.ToTable("sys订单表_D");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys设备表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("产能公式");

                    b.Property<string>("使用部门");

                    b.Property<string>("厂商");

                    b.Property<string>("名称");

                    b.Property<string>("备注");

                    b.Property<string>("属性");

                    b.Property<string>("工作日历");

                    b.Property<decimal?>("序号")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("折旧年限")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("折旧方法");

                    b.Property<string>("是否主线");

                    b.Property<string>("类型");

                    b.Property<string>("编号");

                    b.Property<string>("规格型号");

                    b.Property<DateTime?>("购置时间");

                    b.Property<decimal?>("资产原值")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("RecordId");

                    b.ToTable("sys设备表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys证照表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("品号");

                    b.Property<string>("图片");

                    b.Property<int?>("图片I");

                    b.Property<string>("文件");

                    b.Property<int?>("文件A");

                    b.Property<string>("是否预警");

                    b.Property<DateTime?>("有效日");

                    b.Property<string>("档案号");

                    b.Property<string>("登记人");

                    b.Property<DateTime?>("登记日期");

                    b.Property<string>("说明");

                    b.HasKey("RecordId");

                    b.ToTable("sys证照表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys需求表", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreateOrg");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("CreateUser");

                    b.Property<int?>("EditingUser");

                    b.Property<DateTime?>("LastEditTime");

                    b.Property<int?>("LastEditUser");

                    b.Property<int?>("LockStatus");

                    b.Property<int?>("ReportStatus");

                    b.Property<string>("WorkflowStatus");

                    b.Property<string>("业务类型");

                    b.Property<DateTime?>("交期");

                    b.Property<string>("仓");

                    b.Property<string>("制单");

                    b.Property<string>("单号");

                    b.Property<string>("备注");

                    b.Property<string>("往来");

                    b.Property<string>("往来单号");

                    b.Property<string>("往来号");

                    b.Property<DateTime?>("日期");

                    b.HasKey("RecordId");

                    b.ToTable("sys需求表");
                });

            modelBuilder.Entity("Pinhua2.Data.Models.sys需求表_D", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecordId");

                    b.Property<int?>("Sequence");

                    b.Property<decimal?>("单价")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("单位");

                    b.Property<string>("品号");

                    b.Property<string>("品名");

                    b.Property<string>("品牌");

                    b.Property<string>("备注");

                    b.Property<string>("子单号");

                    b.Property<decimal?>("库存")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("数量")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("状态");

                    b.Property<decimal?>("税率")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("行号");

                    b.Property<string>("规格");

                    b.Property<decimal?>("金额")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Idx");

                    b.ToTable("sys需求表_D");
                });
#pragma warning restore 612, 618
        }
    }
}
